version: '2'
services:
  msweb-app:
    image: mgrweb
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
    ###network_mode: "host"   # please make note of the alignment
  ##msweb-mongodb:
  ##  extends:
  ##    file: mongodb.yml
  ##    service: msweb-mongodb
